/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductId = IDL.Nat;
export const AddReviewInput = IDL.Record({
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Review = IDL.Record({
  'id' : ReviewId,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CouponCode = IDL.Text;
export const CreateCouponInput = IDL.Record({
  'expiryTimestamp' : IDL.Int,
  'active' : IDL.Bool,
  'code' : CouponCode,
  'discountPercent' : IDL.Nat,
});
export const CouponPublic = IDL.Record({
  'expiryTimestamp' : IDL.Int,
  'active' : IDL.Bool,
  'code' : CouponCode,
  'discountPercent' : IDL.Nat,
});
export const ShippingAddress = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : ProductId,
  'price' : IDL.Nat,
});
export const CreateOrderInput = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'shippingAddress' : ShippingAddress,
  'stripePaymentIntentId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const OrderPublic = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : IDL.Opt(IDL.Text),
  'total' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'discount' : IDL.Nat,
  'shippingAddress' : ShippingAddress,
  'stripePaymentIntentId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductInput = IDL.Record({
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'stockByVariant' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'images' : IDL.Vec(ExternalBlob),
});
export const ProductPublic = IDL.Record({
  'id' : ProductId,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'stockByVariant' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'images' : IDL.Vec(ExternalBlob),
});
export const CartItem = IDL.Record({
  'qty' : IDL.Nat,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : ProductId,
});
export const ProductFilters = IDL.Record({
  'sortBy' : IDL.Opt(IDL.Text),
  'page' : IDL.Opt(IDL.Nat),
  'pageSize' : IDL.Opt(IDL.Nat),
  'search' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserAddress = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const UserPublic = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'address' : IDL.Opt(UserAddress),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateUserInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Opt(UserAddress),
});
export const ValidateCouponResult = IDL.Record({
  'valid' : IDL.Bool,
  'discountPercent' : IDL.Nat,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addReview' : IDL.Func([AddReviewInput], [Review], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoupon' : IDL.Func([CreateCouponInput], [CouponPublic], []),
  'createOrder' : IDL.Func([CreateOrderInput], [OrderPublic], []),
  'createProduct' : IDL.Func([ProductInput], [ProductPublic], []),
  'deleteCoupon' : IDL.Func([CouponCode], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductPublic)], ['query']),
  'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getProducts' : IDL.Func(
      [ProductFilters],
      [IDL.Vec(ProductPublic)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([], [UserPublic], []),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCart' : IDL.Func([IDL.Vec(CartItem)], [], []),
  'updateCoupon' : IDL.Func([CouponCode, CreateCouponInput], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
  'updateUserProfile' : IDL.Func([UpdateUserInput], [], []),
  'validateCoupon' : IDL.Func([CouponCode], [ValidateCouponResult], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductId = IDL.Nat;
  const AddReviewInput = IDL.Record({
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Review = IDL.Record({
    'id' : ReviewId,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CouponCode = IDL.Text;
  const CreateCouponInput = IDL.Record({
    'expiryTimestamp' : IDL.Int,
    'active' : IDL.Bool,
    'code' : CouponCode,
    'discountPercent' : IDL.Nat,
  });
  const CouponPublic = IDL.Record({
    'expiryTimestamp' : IDL.Int,
    'active' : IDL.Bool,
    'code' : CouponCode,
    'discountPercent' : IDL.Nat,
  });
  const ShippingAddress = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : ProductId,
    'price' : IDL.Nat,
  });
  const CreateOrderInput = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'shippingAddress' : ShippingAddress,
    'stripePaymentIntentId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const OrderPublic = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'couponCode' : IDL.Opt(IDL.Text),
    'total' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'discount' : IDL.Nat,
    'shippingAddress' : ShippingAddress,
    'stripePaymentIntentId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductInput = IDL.Record({
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'stockByVariant' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'images' : IDL.Vec(ExternalBlob),
  });
  const ProductPublic = IDL.Record({
    'id' : ProductId,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'stockByVariant' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'images' : IDL.Vec(ExternalBlob),
  });
  const CartItem = IDL.Record({
    'qty' : IDL.Nat,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : ProductId,
  });
  const ProductFilters = IDL.Record({
    'sortBy' : IDL.Opt(IDL.Text),
    'page' : IDL.Opt(IDL.Nat),
    'pageSize' : IDL.Opt(IDL.Nat),
    'search' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserAddress = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const UserPublic = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'address' : IDL.Opt(UserAddress),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateUserInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Opt(UserAddress),
  });
  const ValidateCouponResult = IDL.Record({
    'valid' : IDL.Bool,
    'discountPercent' : IDL.Nat,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addReview' : IDL.Func([AddReviewInput], [Review], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoupon' : IDL.Func([CreateCouponInput], [CouponPublic], []),
    'createOrder' : IDL.Func([CreateOrderInput], [OrderPublic], []),
    'createProduct' : IDL.Func([ProductInput], [ProductPublic], []),
    'deleteCoupon' : IDL.Func([CouponCode], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductPublic)], ['query']),
    'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getProducts' : IDL.Func(
        [ProductFilters],
        [IDL.Vec(ProductPublic)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([], [UserPublic], []),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCart' : IDL.Func([IDL.Vec(CartItem)], [], []),
    'updateCoupon' : IDL.Func([CouponCode, CreateCouponInput], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
    'updateUserProfile' : IDL.Func([UpdateUserInput], [], []),
    'validateCoupon' : IDL.Func(
        [CouponCode],
        [ValidateCouponResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };