/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddReviewInput {
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export interface CartItem {
  'qty' : bigint,
  'color' : string,
  'size' : string,
  'productId' : ProductId,
}
export type CouponCode = string;
export interface CouponPublic {
  'expiryTimestamp' : bigint,
  'active' : boolean,
  'code' : CouponCode,
  'discountPercent' : bigint,
}
export interface CreateCouponInput {
  'expiryTimestamp' : bigint,
  'active' : boolean,
  'code' : CouponCode,
  'discountPercent' : bigint,
}
export interface CreateOrderInput {
  'couponCode' : [] | [string],
  'shippingAddress' : ShippingAddress,
  'stripePaymentIntentId' : string,
  'items' : Array<OrderItem>,
}
export type ExternalBlob = Uint8Array;
export type OrderId = bigint;
export interface OrderItem {
  'qty' : bigint,
  'name' : string,
  'color' : string,
  'size' : string,
  'productId' : ProductId,
  'price' : bigint,
}
export interface OrderPublic {
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : [] | [string],
  'total' : bigint,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'discount' : bigint,
  'shippingAddress' : ShippingAddress,
  'stripePaymentIntentId' : string,
  'items' : Array<OrderItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface ProductFilters {
  'sortBy' : [] | [string],
  'page' : [] | [bigint],
  'pageSize' : [] | [bigint],
  'search' : [] | [string],
  'category' : [] | [string],
}
export type ProductId = bigint;
export interface ProductInput {
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
  'stockByVariant' : Array<[string, bigint]>,
  'images' : Array<ExternalBlob>,
}
export interface ProductPublic {
  'id' : ProductId,
  'featured' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'sizes' : Array<string>,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
  'stockByVariant' : Array<[string, bigint]>,
  'images' : Array<ExternalBlob>,
}
export interface Review {
  'id' : ReviewId,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ShippingAddress {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateUserInput {
  'name' : string,
  'email' : string,
  'address' : [] | [UserAddress],
}
export interface UserAddress {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface UserPublic {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'address' : [] | [UserAddress],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValidateCouponResult {
  'valid' : boolean,
  'discountPercent' : bigint,
  'message' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addReview' : ActorMethod<[AddReviewInput], Review>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoupon' : ActorMethod<[CreateCouponInput], CouponPublic>,
  'createOrder' : ActorMethod<[CreateOrderInput], OrderPublic>,
  'createProduct' : ActorMethod<[ProductInput], ProductPublic>,
  'deleteCoupon' : ActorMethod<[CouponCode], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllCoupons' : ActorMethod<[], Array<CouponPublic>>,
  'getAllOrders' : ActorMethod<[], Array<OrderPublic>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getFeaturedProducts' : ActorMethod<[], Array<ProductPublic>>,
  'getMyOrders' : ActorMethod<[], Array<OrderPublic>>,
  'getProduct' : ActorMethod<[ProductId], [] | [ProductPublic]>,
  'getProductReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getProducts' : ActorMethod<[ProductFilters], Array<ProductPublic>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[], UserPublic>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCart' : ActorMethod<[Array<CartItem>], undefined>,
  'updateCoupon' : ActorMethod<[CouponCode, CreateCouponInput], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], undefined>,
  'updateUserProfile' : ActorMethod<[UpdateUserInput], undefined>,
  'validateCoupon' : ActorMethod<[CouponCode], ValidateCouponResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];